#!/usr/bin/env python3
"""
Generate the ESPHome YAML fragment for the CC1101-based fan remote receiver.

Protocol (see protocol.txt for full details):
    - 304.30 MHz OOK at 333 us per chip
    - Each logical bit -> 3 chips: '1', '0', b
    - Message = preamble(4) + FAN_ID(14) + cmdid(7) = 25 bits = 75 chips
    - Captured pulse list naturally ends at the last HIGH chip of the message
      because all cmdids end in '0' and the trailing LOW chips merge with
      the inter-burst pause. Result: 49-pulse patterns ending on +333.

No per-fan transformations — every fan uses the same cmdid table; FAN_IDs
are 14-bit unique addresses.
"""

import os
import sys
import yaml

CHIP_US  = 333
PREAMBLE = "1111"

CMDS = {
    'reverse': '0001000',
    'light':   '0000010',
    'stop':    '0000100',
    'speed1':  '0010000',
    'speed2':  '0010100',
    'speed3':  '0100000',
    'speed4':  '0110000',
    'speed5':  '1000100',
    'speed6':  '1000000',
    'pair':    '0100100',
}

def _load_fan_ids():
    """Load FAN_IDs from config.yaml next to this script. Same source of
    truth as control_fan.py and decode_fan_remote.py."""
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'config.yaml')
    with open(path) as f:
        cfg = yaml.safe_load(f) or {}
    fans = cfg.get('fans') or {}
    if not fans:
        sys.exit(f"error: no 'fans' dict in {path}")
    return fans


FAN_IDS = _load_fan_ids()


def bits_to_chips(bits):
    return ''.join(f"10{b}" for b in bits)


def chips_to_pulses(chips, chip_us=CHIP_US):
    pulses, i = [], 0
    while i < len(chips):
        level = chips[i]
        run = 1
        while i + run < len(chips) and chips[i + run] == level:
            run += 1
        dur = run * chip_us
        pulses.append(dur if level == '1' else -dur)
        i += run
    return pulses


def build_pulses(fan_id, cmdid):
    """Build the raw +/- us pulse list for one button press.

    The 25-bit message encodes to 75 chips. The final two chips of bit 24
    (always '00' since every cmdid ends in '0') merge with the inter-burst
    pause and aren't visible in the captured pulse list, so we drop the
    trailing negative pulse to make the pattern match what the receiver
    actually sees.
    """
    full_bits = PREAMBLE + fan_id + cmdid
    assert len(full_bits) == 25, f"Expected 25 bits, got {len(full_bits)}"
    pulses = chips_to_pulses(bits_to_chips(full_bits))
    while pulses and pulses[-1] < 0:
        pulses.pop()
    return pulses


def emit_binary_sensor(room, cmd_name, fan_id, cmdid):
    pulses = build_pulses(fan_id, cmdid)
    pulses_str = ', '.join(str(p) for p in pulses)
    label = f"Fan {room} {cmd_name}"
    return (
        f"  - platform: remote_receiver\n"
        f"    name: \"{label}\"\n"
        f"    id: fan_{room}_{cmd_name}\n"
        f"    raw:\n"
        f"      code: [{pulses_str}]\n"
        f"    on_press:\n"
        f"      then:\n"
        f"        - logger.log:\n"
        f"            level: INFO\n"
        f"            tag: \"fan-remote\"\n"
        f"            format: \"%s pressed\"\n"
        f"            args: ['\"{label}\"']\n"
    )


def main():
    print("# Auto-generated by generate_esphome_config.py")
    print("# Patterns: 25-bit messages = preamble(4) + FAN_ID(14) + cmdid(7)")
    print("binary_sensor:")
    for room, fan_id in FAN_IDS.items():
        assert len(fan_id) == 14, f"FAN_ID for {room} must be 14 bits"
        for cmd_name, cmdid in CMDS.items():
            assert len(cmdid) == 7, f"cmdid for {cmd_name} must be 7 bits"
            print(emit_binary_sensor(room, cmd_name, fan_id, cmdid))


if __name__ == '__main__':
    main()
