#!/bin/sh

DAEMON="onlyfansd"
DAEMON_BIN="/usr/bin/onlyfansd"
DAEMON_CONF="/etc/onlyfansd/config.yaml"
PIDFILE="/var/run/onlyfansd.pid"
LOGFILE="/var/log/onlyfansd.log"
RUNDIR="/var/lib/onlyfansd"

start() {
	printf "Starting %s: " "$DAEMON"
	mkdir -p "$RUNDIR"
	start-stop-daemon -S -b -m -p "$PIDFILE" \
		-d "$RUNDIR" \
		-x "$DAEMON_BIN" -- "$DAEMON_CONF" \
		>> "$LOGFILE" 2>&1
	echo "OK"
}

stop() {
	printf "Stopping %s: " "$DAEMON"
	start-stop-daemon -K -p "$PIDFILE"
	echo "OK"
}

case "$1" in
	start)   start ;;
	stop)    stop ;;
	restart) stop; sleep 1; start ;;
	*)       echo "Usage: $0 {start|stop|restart}"; exit 1 ;;
esac
